### PR TITLE
Cert perspectives fix

### LINKED ISSUE #171: names field doesn't capture redacted names
Because ?.domain.com isn't technically a valid name, this won't end up being put into the `names` array. We should make our domain validator less strict to accept these. The names field is already a custom construct and given that we want to support easily searching for certificates, it makes the most sense to just include these.

### PR DESCRIPTION
**Pull request by umbernhard**
Fixed #171 and #186

### CODE REVIEW

**Comment by umbernhard** [comment]
Tested against https://censys.io/certificates/b354890665fd2e05f13a6a029eeb701b7f8dd6f45f14d68f7bfa2f9a7d41470c

and 

https://censys.io/certificates/719c282a51e935051e88bf6115dda0731da21c0e12c08e6bcea36078e83e4966

File: ztools/x509/json.go [hunk 1]
```diff
@@ -228,37 +229,41 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
-				flag = govalidator.IsURL(name)
-			}
+	name := c.Subject.CommonName
+	isValid := false
+
+	if len(name) > 2 && name[0] == '*' {
+		isValid = govalidator.IsURL(name[2:])
+	} else if len(name) > 2 && name[0] == '?' {
+		isValid = isValid || govalidator.IsURL(name[2:])
+	} else if !strings.Contains(name, ".") {
```
Comment (umbernhard) [inline ztools/x509/json.go]: It won't, because of line 232 in this commit: https://github.com/zmap/zgrab/commit/adccb4b0c2d79ad4d171ecbcc9f7921d2631284f#diff-b69ed0926a8809fc22de87e608774fe9R232

File: ztools/x509/json.go [hunk 2]
```diff
@@ -228,37 +229,41 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
-
-			if len(name) > 2 && name[0] == '*' {
-				flag = govalidator.IsURL(name[2:])
-			} else {
-				flag = govalidator.IsURL(name)
-			}
+	name := c.Subject.CommonName
+	isValid := false
+
+	if len(name) > 2 && name[0] == '*' {
```
Comment (dadrian) [inline ztools/x509/json.go]: Shouldn't we look at `name[1]` ever?

Comment (umbernhard) [inline ztools/x509/json.go]: so the reason for this is that govalidator won't validate *.blah.com. Will *a.blah.com ever be possible?

Comment (zakird) [inline ztools/x509/json.go]: Knowing how _terrible_ people are at making certs..... probably.

Comment (umbernhard) [inline ztools/x509/json.go]: Right. So should we consider that valid or not? 

@dadrian's right that I should look at names[1], there could be a weird case of *abc.blah.com, where this code would check c.blah.com as a result, which is *technically* valid but meaningless. I'll make this more robust.

File: ztools/x509/json.go (hunk 1 above)
Comment (umbernhard) [inline ztools/x509/json.go]: Never mind, I'm dumb. Will fix.

File: ztools/x509/json.go [hunk 3]
```diff
@@ -228,37 +229,40 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
+	isValid := false
+
+	// Check for wildcards and redacts, ignore malformed urls
+	if len(name) > 2 && name[0] == '*' && name[1] == '.' {
+		isValid = govalidator.IsURL(name[2:])
+	} else if len(name) > 2 && name[0] == '?' && name[1] == '.' {
+		isValid = isValid || govalidator.IsURL(name[2:])
+	} else {
+		isValid = govalidator.IsURL(name)
+	}
```
Comment (dadrian) [inline ztools/x509/json.go]: Can we extract this whole chunk of logic to a function, since it's repeated in the `DNSNames` loop later.

File: ztools/x509/json.go [hunk 4]
```diff
@@ -228,37 +229,40 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
+			// If this is just a TLD cert, it's valid
+			isValid = true
 		} else {
-			flag = govalidator.IsURL(name)
+			isValid = govalidator.IsURL(name)
 		}
 
-		if flag {
+		if isValid {
 			jc.Names = append(jc.Names, name)
```
Comment (dadrian) [inline ztools/x509/json.go]: This doesn't look deduplicated.

File: ztools/x509/json.go [hunk 5]
```diff
@@ -228,37 +229,40 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
-			} else {
-				flag = govalidator.IsURL(name)
-			}
+	name := c.Subject.CommonName
+	isValid := false
+
+	// Check for wildcards and redacts, ignore malformed urls
+	if len(name) > 2 && name[0] == '*' && name[1] == '.' {
+		isValid = govalidator.IsURL(name[2:])
+	} else if len(name) > 2 && name[0] == '?' && name[1] == '.' {
```
Comment (umbernhard) [inline ztools/x509/json.go]: This still leaves us open to *abc.x.y, since it would leave us with bc.x.y, which govalidator would see as valid. Is there like a regex or something to let us specify StartsWith(name, "*?[.]" or something?

File: ztools/x509/json.go (hunk 3 above)
Comment (umbernhard) [inline ztools/x509/json.go]: good point, I can do that.

File: ztools/x509/json.go [hunk 6]
```diff
@@ -228,37 +229,40 @@ func (c *Certificate) MarshalJSON() ([]byte, error) {
...
-		flag := false
+		isValid := false
 
-		if len(name) > 2 && name[0] == '*' {
-			flag = govalidator.IsURL(name[2:])
+		// Check wildcards, redacts, malformed, and tlds
+		if len(name) > 2 && name[0] == '*' && name[1] == '.' {
+			isValid = govalidator.IsURL(name[2:])
+		} else if len(name) > 2 && name[0] == '?' && name[1] == '.' {
+			isValid = isValid || govalidator.IsURL(name[2:])
```
Comment (umbernhard) [inline ztools/x509/json.go]: Realized that this `or` is no longer needed

File: ztools/x509/json.go (hunk 4 above)
Comment (umbernhard) [inline ztools/x509/json.go]: IIRC, deduplication happens later.

File: ztools/x509/json.go (hunk 3 above)
Comment (umbernhard) [inline ztools/x509/json.go]: Hmm, actually I'm realizing the logic isn't repeated exactly. For DNSNames we also check for TLDs

Comment (umbernhard) [inline ztools/x509/json.go]: Figured out a way to make it work.

File: ztools/x509/json.go (hunk 4 above)
Comment (umbernhard) [inline ztools/x509/json.go]: Ah yes, see https://github.com/zmap/zgrab/blob/certPerspectivesFix/ztools/x509/json.go#L283

**Comment by umbernhard** [comment]
@dadrian I think I made the fix you requested.

File: ztools/x509/json.go (hunk 5 above)
Comment (dadrian) [inline ztools/x509/json.go]: Whomp, I meant:
```
if strings.StartsWith(name, "*.") {
    isValid = govalidator.IsURL(name[2:])
} else if strings.StartsWith(name, "?.") {
    isValid = govalidator.IsURL(name[2:])
} else {
    isValid = govalidator.IsURL(name)
}
```

Comment (umbernhard) [inline ztools/x509/json.go]: Is done.

File: ztools/x509/json.go [hunk 7]
```diff
@@ -356,3 +334,15 @@ func purgeNameDuplicates(names []string) (out []string) {
 	}
 	return
 }
+
+func isValid(name string) (ret bool) {
+
```
Comment (dadrian) [inline ztools/x509/json.go]: Maye name `isValidName`?

**Comment by dadrian** [comment]
Is `?.?.example.com` allowed? @zakird

**Comment by zakird** [comment]
I mean there aren't any real rules.

**Comment by dadrian** [comment]
Should we handle that?

**Comment by dadrian** [comment]
I'm good to merge if @zakird is.

**Comment by umbernhard** [comment]
I would suggest checking for the ?.? case and at least noting that it happens, but I don't really know how big a deal it is.

**Comment by umbernhard** [comment]
or if it would materially change anything

**Comment by zakird** [comment]
This looks good to me. I'm not too worried about the ?.? situation, I'm not seeing evidence of this happening in practice.
